using System.Text;
using System.Collections.Generic;
using ZeroReflection.Mapper.CodeGeneration.Models;
using ZeroReflection.Mapper.CodeGeneration.Utils;

namespace ZeroReflection.Mapper.CodeGeneration.Emit
{
    internal static class ServiceRegistrationEmitter
    {
        public static string Build(List<MappingInfo> mappings)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using ZeroReflection.Mapper;");
            foreach (var ns in CodeGenUtils.GetRequiredNamespaces(mappings))
                sb.AppendLine($"using {ns};");
            sb.AppendLine();
            sb.AppendLine("namespace ZeroReflection.Mapper.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class MappingServiceExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IServiceCollection RegisterZeroReflectionMapping(this IServiceCollection services, System.Action<MapperConfiguration> configure = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            services.AddSingleton<IMapper, Mapper>();");
            sb.AppendLine("            services.AddSingleton<IGeneratedMappingDispatcher, GeneratedMappingDispatcher>();");
            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}