using System.Collections.Generic;
using System.Linq;
using System.Text;
using ZeroReflection.MapperGenerator.Models;
using ZeroReflection.MapperGenerator.Utils;

namespace ZeroReflection.MapperGenerator.Emit
{
    internal static class DispatcherEmitter
    {
        public static string Build(List<MappingInfo> mappings)
        {
            var unique = CodeGenUtils.GetUniquePairs(mappings);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using ZeroReflection.Mapper;");
            foreach (var ns in CodeGenUtils.GetRequiredNamespaces(mappings))
                sb.AppendLine($"using {ns};");
            sb.AppendLine();
            sb.AppendLine("namespace ZeroReflection.Mapper.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class __GeneratedMappingDispatcherStatic");
            sb.AppendLine("    {");

            if (mappings.Any() && mappings.First().UseSwitchDispatcher)
            {
                sb.AppendLine("        private static readonly System.Collections.Generic.Dictionary<(System.Type, System.Type), int> _arrayMapIndex = new()");
                sb.AppendLine("        {");
                int ai = 1;
                foreach (var (src, dst) in unique)
                    sb.AppendLine($"            {{ (typeof({src}[]), typeof({dst}[])), {ai++} }},");
                sb.AppendLine("        };");
                sb.AppendLine();

                sb.AppendLine("        private static readonly System.Collections.Generic.Dictionary<(System.Type, System.Type), int> _listMapIndex = new()");
                sb.AppendLine("        {");
                int li = 1;
                foreach (var (src, dst) in unique)
                    sb.AppendLine($"            {{ (typeof(System.Collections.Generic.List<{src}>), typeof(System.Collections.Generic.List<{dst}>)), {li++} }},");
                sb.AppendLine("        };");
                sb.AppendLine();

                sb.AppendLine("        private static readonly System.Collections.Generic.Dictionary<(System.Type, System.Type), int> _objectMapIndex = new()");
                sb.AppendLine("        {");
                int oi = 1;
                foreach (var (src, dst) in unique)
                {
                    var mapping = mappings.FirstOrDefault(m => m.Source == src && m.Destination == dst);
                    if (mapping != null)
                        sb.AppendLine($"            {{ (typeof({src}), typeof({dst})), {oi++} }},");
                }
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            // Array
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        internal static bool TryMapArray(object source, Type sourceType, Type destType, out object result)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (source is null) { result = null!; return true; }");
            if (mappings.Any() && mappings.First().UseSwitchDispatcher)
            {
                sb.AppendLine("            if (!_arrayMapIndex.TryGetValue((sourceType, destType), out int key)) { result = null!; return false; }");
                sb.AppendLine("            switch (key)");
                sb.AppendLine("            {");
                int ai2 = 1;
                foreach (var (src, dst) in unique)
                {
                    sb.AppendLine($"                case {ai2++}: result = Map{src}To{dst}.MapArrayTo{dst}(({src}[])source)!; return true;");
                }
                sb.AppendLine("                default: result = null!; return false;");
                sb.AppendLine("            }");
            }
            else
            {
                foreach (var (src, dst) in unique)
                    sb.AppendLine($"            if (sourceType == typeof({src}[]) && destType == typeof({dst}[])) {{ result = Map{src}To{dst}.MapArrayTo{dst}(({src}[])source)!; return true; }}");
                sb.AppendLine("            result = null!; return false;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // List
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        internal static bool TryMapList(object source, Type sourceType, Type destType, out object result)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (source is null) { result = null!; return true; }");
            if (mappings.Any() && mappings.First().UseSwitchDispatcher)
            {
                sb.AppendLine("            if (!_listMapIndex.TryGetValue((sourceType, destType), out int key)) { result = null!; return false; }");
                sb.AppendLine("            switch (key)");
                sb.AppendLine("            {");
                int li2 = 1;
                foreach (var (src, dst) in unique)
                {
                    sb.AppendLine($"                case {li2++}: result = Map{src}To{dst}.MapListTo{dst}((System.Collections.Generic.List<{src}>)source)!; return true;");
                }
                sb.AppendLine("                default: result = null!; return false;");
                sb.AppendLine("            }");
            }
            else
            {
                foreach (var (src, dst) in unique)
                    sb.AppendLine($"            if (sourceType == typeof(System.Collections.Generic.List<{src}>) && destType == typeof(System.Collections.Generic.List<{dst}>)) {{ result = Map{src}To{dst}.MapListTo{dst}((System.Collections.Generic.List<{src}>)source)!; return true; }}");
                sb.AppendLine("            result = null!; return false;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // Single
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        internal static bool TryMapSingleObject(object source, Type sourceType, Type destType, out object result)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (source is null) { result = null!; return true; }");
            if (mappings.Any() && mappings.First().UseSwitchDispatcher)
            {
                sb.AppendLine("            if (!_objectMapIndex.TryGetValue((sourceType, destType), out int key)) { result = null!; return false; }");
                sb.AppendLine("            switch (key)");
                sb.AppendLine("            {");
                int oi2 = 1;
                foreach (var (src, dst) in unique)
                {
                    var mapping = mappings.FirstOrDefault(m => m.Source == src && m.Destination == dst);
                    if (mapping != null)
                        sb.AppendLine($"                case {oi2++}: result = (({src})source).MapTo{dst}(); return true;");
                }
                sb.AppendLine("                default: result = null!; return false;");
                sb.AppendLine("            }");
            }
            else
            {
                foreach (var (src, dst) in unique)
                {
                    var mapping = mappings.FirstOrDefault(m => m.Source == src && m.Destination == dst);
                    if (mapping != null)
                        sb.AppendLine($"            if (sourceType == typeof({src}) && destType == typeof({dst})) {{ result = (({src})source).MapTo{dst}(); return true; }}");
                    else
                        sb.AppendLine($"            // No mapping method for {src} => {dst}");
                }
                sb.AppendLine("            result = null!; return false;");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public sealed class GeneratedMappingDispatcher : IGeneratedMappingDispatcher");
            sb.AppendLine("    {");
            sb.AppendLine("        public bool TryMapArray(object source, Type sourceType, Type destType, out object result) => __GeneratedMappingDispatcherStatic.TryMapArray(source, sourceType, destType, out result);");
            sb.AppendLine("        public bool TryMapList(object source, Type sourceType, Type destType, out object result) => __GeneratedMappingDispatcherStatic.TryMapList(source, sourceType, destType, out result);");
            sb.AppendLine("        public bool TryMapSingleObject(object source, Type sourceType, Type destType, out object result) => __GeneratedMappingDispatcherStatic.TryMapSingleObject(source, sourceType, destType, out result);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
