using System.Text;
using System.Collections.Generic;
using System.Linq;
using ZeroReflection.ApiGenerator.Models;

namespace ZeroReflection.ApiGenerator.Emit;

internal static class JsonContextEmitter
{
    public static string GenerateJsonContext(IEnumerable<ControllerInfo> controllers, string rootNamespace = "AotSample")
    {
        var sb = new StringBuilder();
        var allTypes = new HashSet<string>();
        
        // Collect all unique types from endpoints
        foreach (var controller in controllers)
        {
            foreach (var endpoint in controller.Endpoints)
            {
                // Add response type
                if (!string.IsNullOrEmpty(endpoint.ResponseType))
                {
                    var cleanType = CleanTypeName(endpoint.ResponseType);
                    allTypes.Add(cleanType);
                }
                
                // Add parameter types
                foreach (var param in endpoint.Parameters)
                {
                    if (param.Source == "body" && !string.IsNullOrEmpty(param.Type))
                    {
                        var cleanType = CleanTypeName(param.Type);
                        allTypes.Add(cleanType);
                    }
                }
            }
        }
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        
        // Add namespaces for discovered types
        var namespaces = allTypes
            .Select(t => ExtractNamespace(t))
            .Where(ns => !string.IsNullOrEmpty(ns))
            .Distinct()
            .OrderBy(ns => ns);
            
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Generated;");
        sb.AppendLine();
        
        // Generate JSON context
        sb.AppendLine("[JsonSerializable(typeof(object))]");
        sb.AppendLine("[JsonSerializable(typeof(string))]");
        sb.AppendLine("[JsonSerializable(typeof(int))]");
        sb.AppendLine("[JsonSerializable(typeof(Dictionary<string, object>))]");
        
        foreach (var type in allTypes.OrderBy(t => t))
        {
            sb.AppendLine($"[JsonSerializable(typeof({type}))]");
        }
        
        sb.AppendLine("[JsonSourceGenerationOptions(WriteIndented = true)]");
        sb.AppendLine("internal partial class GeneratedApiJsonContext : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    private static string CleanTypeName(string typeName)
    {
        // Remove Task<> wrapper
        if (typeName.StartsWith("System.Threading.Tasks.Task<") && typeName.EndsWith(">"))
        {
            typeName = typeName.Substring("System.Threading.Tasks.Task<".Length);
            typeName = typeName.Substring(0, typeName.Length - 1);
        }
        
        // Keep as-is for now (including generics like List<T>)
        return typeName;
    }
    
    private static string ExtractNamespace(string fullTypeName)
    {
        // Handle generics like List<UserModel>
        var typeWithoutGenerics = fullTypeName.Split('<')[0];
        
        var lastDot = typeWithoutGenerics.LastIndexOf('.');
        if (lastDot > 0)
        {
            return typeWithoutGenerics.Substring(0, lastDot);
        }
        
        return string.Empty;
    }
}
