using System.Collections.Generic;
using System.Linq;
using System.Text;
using ZeroReflection.ApiGenerator.Models;

namespace ZeroReflection.ApiGenerator.Emit;

internal static class RouteDispatcherEmitter
{
    public static string Generate(IEnumerable<ControllerInfo> controllers, HashSet<string> namespaces, string rootNamespace = "AotSample", string jsonContextName = "AotJsonContext")
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroReflection.Api;");
        sb.AppendLine($"using {rootNamespace};");
        
        foreach (var ns in namespaces.OrderBy(n => n))
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedApiRouter");
        sb.AppendLine("{");
        sb.AppendLine("    public static void RegisterControllers(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var controller in controllers)
        {
            sb.AppendLine($"        services.AddTransient<{controller.FullName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static async Task<RouteResult> RouteAsync(");
        sb.AppendLine("        string path,");
        sb.AppendLine("        string method,");
        sb.AppendLine("        Dictionary<string, string> routeValues,");
        sb.AppendLine("        Dictionary<string, string> queryValues,");
        sb.AppendLine("        Dictionary<string, string> headers,");
        sb.AppendLine("        string? body,");
        sb.AppendLine("        IServiceProvider serviceProvider,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        path = path.ToLowerInvariant().TrimEnd('/');");
        sb.AppendLine("        method = method.ToUpperInvariant();");
        sb.AppendLine();

        foreach (var controller in controllers)
        {
            GenerateControllerRouting(sb, controller, jsonContextName);
        }

        sb.AppendLine("        return RouteResult.NotFound();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static bool MatchesRoute(string actualPath, string pattern, out Dictionary<string, string> routeValues)");
        sb.AppendLine("    {");
        sb.AppendLine("        routeValues = new Dictionary<string, string>();");
        sb.AppendLine("        var actualParts = actualPath.Trim('/').Split('/');");
        sb.AppendLine("        var patternParts = pattern.Trim('/').Split('/');");
        sb.AppendLine("        if (actualParts.Length != patternParts.Length) return false;");
        sb.AppendLine("        for (int i = 0; i < patternParts.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var patternPart = patternParts[i];");
        sb.AppendLine("            var actualPart = actualParts[i];");
        sb.AppendLine("            if (patternPart.StartsWith(\"{\") && patternPart.EndsWith(\"}\"))");
        sb.AppendLine("            {");
        sb.AppendLine("                var paramName = patternPart.Trim('{', '}');");
        sb.AppendLine("                routeValues[paramName] = actualPart;");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (!patternPart.Equals(actualPart, StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("            {");
        sb.AppendLine("                return false;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        return true;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateControllerRouting(StringBuilder sb, ControllerInfo controller, string jsonContextName)
    {
        var baseRoute = "/" + controller.Route.TrimStart('/').TrimEnd('/').ToLowerInvariant();
        
        sb.AppendLine($"        // {controller.Name} routes");
        sb.AppendLine($"        if (path.StartsWith(\"{baseRoute}\"))");
        sb.AppendLine("        {");
        sb.AppendLine($"            var controller = serviceProvider.GetRequiredService<{controller.FullName}>();");
        sb.AppendLine();

        foreach (var endpoint in controller.Endpoints)
        {
            GenerateEndpointRouting(sb, controller, endpoint, baseRoute, jsonContextName);
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void GenerateEndpointRouting(StringBuilder sb, ControllerInfo controller, EndpointInfo endpoint, string baseRoute, string jsonContextName)
    {
        var fullRoute = CombineRoutes(baseRoute, endpoint.Route);
        var routePattern = ConvertToRoutePattern(fullRoute);
        var hasRouteParams = routePattern.Contains("{");

        sb.AppendLine($"            // {endpoint.HttpMethod} {fullRoute} - {endpoint.Summary}");
        
        if (hasRouteParams)
        {
            sb.AppendLine($"            if (method == \"{endpoint.HttpMethod}\" && MatchesRoute(path, \"{routePattern}\", out var routeParams_{endpoint.MethodName}))");
        }
        else
        {
            sb.AppendLine($"            if (method == \"{endpoint.HttpMethod}\" && path == \"{routePattern}\")");
        }
        
        sb.AppendLine("            {");
        sb.AppendLine("                try");
        sb.AppendLine("                {");

        // Generate parameter extraction for body params
        foreach (var param in endpoint.Parameters)
        {
            if (param.Source == "body")
            {
                var localVar = $"bodyParam_{param.Name}";
                if (param.Type == "string" || param.Type == "string?")
                {
                    sb.AppendLine($"                    var {localVar} = body ?? string.Empty;");
                }
                else
                {
                    sb.AppendLine($"                    var {localVar} = System.Text.Json.JsonSerializer.Deserialize(body ?? \"{{}}\", typeof({param.Type}), {jsonContextName}.Default) as {param.Type};");
                    sb.AppendLine($"                    if ({localVar} == null) return RouteResult.BadRequest(\"Invalid request body\");");
                }
            }
        }

        // Build method call
        var callParams = new List<string>();
        foreach (var param in endpoint.Parameters)
        {
            if (param.Source == "body")
            {
                callParams.Add($"bodyParam_{param.Name}");
            }
            else if (param.Source == "queryValues")
            {
                callParams.Add("queryValues");
            }
            else if (param.Source == "headers")
            {
                callParams.Add("headers");
            }
            else if (param.Source == "route")
            {
                if (hasRouteParams)
                {
                    var routeRawExpr = $"routeParams_{endpoint.MethodName}[\"{param.Name}\"]";
                    var routeConvertedExpr = param.Type == "string" || param.Type == "string?"
                        ? routeRawExpr
                        : GetQueryValueParseExpression(param.Type, routeRawExpr);
                    sb.AppendLine($"                    var {param.Name} = {routeConvertedExpr};");
                    callParams.Add(param.Name);
                }
            }
            else if (param.Source == "query")
            {
                var parseExpr = GetQueryValueParseExpression(param.Type, $"{param.Name}Value");
                sb.AppendLine($"                    var {param.Name} = queryValues.TryGetValue(\"{param.Name}\", out var {param.Name}Value) ? {parseExpr} : default({param.Type});");
                callParams.Add(param.Name);
            }
            else if (param.Source == "services")
            {
                sb.AppendLine($"                    var {param.Name} = serviceProvider.GetRequiredService<{param.Type}>();");
                callParams.Add(param.Name);
            }
            else if (param.Source == "cancellationToken")
            {
                callParams.Add("cancellationToken");
            }
        }

        var methodCall = $"controller.{endpoint.MethodName}({string.Join(", ", callParams)})";
        var rt = endpoint.ResponseType;
        var isTask = IsTaskType(rt);
        var isVoidTask = IsVoidTaskType(rt);
        var innerType = isTask && !isVoidTask ? GetTaskInnerType(rt) : rt;
        var isApiGatewayResponse = innerType.Contains("APIGatewayProxyResponse");
        var isGenericActionResult = innerType.Contains("ActionResult<");
        var isIActionResult = !isGenericActionResult &&
                              (innerType.Contains("IActionResult") ||
                               (innerType.Contains("ActionResult") && !innerType.Contains("<")));

        if (isTask)
        {
            if (isVoidTask)
            {
                sb.AppendLine($"                    await {methodCall};");
                sb.AppendLine("                    return RouteResult.Ok();");
            }
            else if (isApiGatewayResponse)
            {
                sb.AppendLine($"                    var agr_{endpoint.MethodName} = await {methodCall};");
                sb.AppendLine($"                    return new ZeroReflection.Api.RouteResult {{ StatusCode = agr_{endpoint.MethodName}.StatusCode, SerializedJson = agr_{endpoint.MethodName}.Body }};");
            }
            else if (isGenericActionResult)
            {
                var dataType = GetActionResultInnerType(innerType);
                sb.AppendLine($"                    var actionResult = await {methodCall};");
                sb.AppendLine($"                    {dataType}? typedResult_{endpoint.MethodName};");
                sb.AppendLine("                    if (actionResult.Result is Microsoft.AspNetCore.Mvc.ObjectResult objResult)");
                sb.AppendLine($"                        typedResult_{endpoint.MethodName} = objResult.Value as {dataType};");
                sb.AppendLine("                    else");
                sb.AppendLine($"                        typedResult_{endpoint.MethodName} = actionResult.Value;");
                sb.AppendLine($"                    var typeInfo_{endpoint.MethodName} = {jsonContextName}.Default.GetTypeInfo(typeof({dataType}));");
                sb.AppendLine($"                    if (typeInfo_{endpoint.MethodName} != null)");
                sb.AppendLine($"                        return RouteResult.OkJson(System.Text.Json.JsonSerializer.Serialize(typedResult_{endpoint.MethodName}, typeInfo_{endpoint.MethodName}));");
                sb.AppendLine($"                    return RouteResult.Ok(typedResult_{endpoint.MethodName});");
            }
            else if (isIActionResult)
            {
                sb.AppendLine($"                    var iActionResult = await {methodCall};");
                sb.AppendLine("                    if (iActionResult is Microsoft.AspNetCore.Mvc.ObjectResult objResult)");
                sb.AppendLine("                        return RouteResult.Ok(objResult.Value);");
                sb.AppendLine("                    if (iActionResult is Microsoft.AspNetCore.Mvc.StatusCodeResult scResult)");
                sb.AppendLine("                        return new ZeroReflection.Api.RouteResult { StatusCode = scResult.StatusCode };");
                sb.AppendLine("                    return RouteResult.Ok();");
            }
            else
            {
                sb.AppendLine($"                    var result_{endpoint.MethodName} = await {methodCall};");
                sb.AppendLine($"                    var typeInfo_{endpoint.MethodName} = {jsonContextName}.Default.GetTypeInfo(typeof({innerType}));");
                sb.AppendLine($"                    if (typeInfo_{endpoint.MethodName} != null)");
                sb.AppendLine($"                        return RouteResult.OkJson(System.Text.Json.JsonSerializer.Serialize(result_{endpoint.MethodName}, typeInfo_{endpoint.MethodName}));");
                sb.AppendLine($"                    return RouteResult.Ok(result_{endpoint.MethodName});");
            }
        }
        else if (isApiGatewayResponse)
        {
            sb.AppendLine($"                    var agr_{endpoint.MethodName} = {methodCall};");
            sb.AppendLine($"                    return new ZeroReflection.Api.RouteResult {{ StatusCode = agr_{endpoint.MethodName}.StatusCode, SerializedJson = agr_{endpoint.MethodName}.Body }};");
        }
        else if (isGenericActionResult)
        {
            var dataType = GetActionResultInnerType(innerType);
            sb.AppendLine($"                    var actionResult = {methodCall};");
            sb.AppendLine($"                    {dataType}? typedResult_{endpoint.MethodName};");
            sb.AppendLine("                    if (actionResult.Result is Microsoft.AspNetCore.Mvc.ObjectResult objResult)");
            sb.AppendLine($"                        typedResult_{endpoint.MethodName} = objResult.Value as {dataType};");
            sb.AppendLine("                    else");
            sb.AppendLine($"                        typedResult_{endpoint.MethodName} = actionResult.Value;");
            sb.AppendLine($"                    var typeInfo_{endpoint.MethodName} = {jsonContextName}.Default.GetTypeInfo(typeof({dataType}));");
            sb.AppendLine($"                    if (typeInfo_{endpoint.MethodName} != null)");
            sb.AppendLine($"                        return RouteResult.OkJson(System.Text.Json.JsonSerializer.Serialize(typedResult_{endpoint.MethodName}, typeInfo_{endpoint.MethodName}));");
            sb.AppendLine($"                    return RouteResult.Ok(typedResult_{endpoint.MethodName});");
        }
        else if (isIActionResult)
        {
            sb.AppendLine($"                    var iActionResult = {methodCall};");
            sb.AppendLine("                    if (iActionResult is Microsoft.AspNetCore.Mvc.ObjectResult objResult)");
            sb.AppendLine("                        return RouteResult.Ok(objResult.Value);");
            sb.AppendLine("                    if (iActionResult is Microsoft.AspNetCore.Mvc.StatusCodeResult scResult)");
            sb.AppendLine("                        return new ZeroReflection.Api.RouteResult { StatusCode = scResult.StatusCode };");
            sb.AppendLine("                    return RouteResult.Ok();");
        }
        else
        {
            sb.AppendLine($"                    var result_{endpoint.MethodName} = {methodCall};");
            sb.AppendLine($"                    var typeInfo_{endpoint.MethodName} = {jsonContextName}.Default.GetTypeInfo(typeof({innerType}));");
            sb.AppendLine($"                    if (typeInfo_{endpoint.MethodName} != null)");
            sb.AppendLine($"                        return RouteResult.OkJson(System.Text.Json.JsonSerializer.Serialize(result_{endpoint.MethodName}, typeInfo_{endpoint.MethodName}));");
            sb.AppendLine($"                    return RouteResult.Ok(result_{endpoint.MethodName});");
        }

        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex)");
        sb.AppendLine("                {");
        sb.AppendLine("                    return RouteResult.ServerError(ex.Message);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();
    }

    private static string GetActionResultInnerType(string innerType)
    {
        const string marker = "ActionResult<";
        var start = innerType.IndexOf(marker);
        if (start < 0) return innerType;
        start += marker.Length;
        var depth = 1;
        var i = start;
        while (i < innerType.Length)
        {
            if (innerType[i] == '<') { depth++; i++; }
            else if (innerType[i] == '>') { depth--; if (depth == 0) break; i++; }
            else i++;
        }
        return innerType.Substring(start, i - start);
    }

    private static bool IsTaskType(string responseType) =>
        responseType == "Task" ||
        responseType == "System.Threading.Tasks.Task" ||
        responseType.StartsWith("Task<") ||
        responseType.StartsWith("System.Threading.Tasks.Task<");

    private static bool IsVoidTaskType(string responseType) =>
        responseType == "Task" || responseType == "System.Threading.Tasks.Task";

    private static string GetTaskInnerType(string responseType)
    {
        var start = responseType.IndexOf('<');
        if (start < 0) return responseType;
        return responseType.Substring(start + 1, responseType.Length - start - 2);
    }

    private static string GetQueryValueParseExpression(string typeName, string valueName)
    {
        var cleanType = typeName.TrimEnd('?');
        return cleanType switch
        {
            "int" or "System.Int32" => $"int.Parse({valueName})",
            "long" or "System.Int64" => $"long.Parse({valueName})",
            "double" or "System.Double" => $"double.Parse({valueName}, System.Globalization.CultureInfo.InvariantCulture)",
            "float" or "System.Single" => $"float.Parse({valueName}, System.Globalization.CultureInfo.InvariantCulture)",
            "bool" or "System.Boolean" => $"bool.Parse({valueName})",
            "System.Guid" => $"System.Guid.Parse({valueName})",
            _ => valueName
        };
    }

    private static string CombineRoutes(string baseRoute, string? endpointRoute)
    {
        if (string.IsNullOrEmpty(endpointRoute))
            return baseRoute;

        return baseRoute.TrimEnd('/') + "/" + endpointRoute!.TrimStart('/');
    }

    private static string ConvertToRoutePattern(string route)
    {
        return route.ToLowerInvariant();
    }
}
