using System;
using System.IO;
using System.Reflection;
using System.Text;

namespace ZeroReflection.ApiGenerator.Emit;

internal static class SwaggerUIEmitter
{
    public static string GenerateSwaggerUI(string rootNamespace = "AotSample", string jsonContextName = "AotJsonContext")
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine($"using {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class SwaggerUIMiddleware");
        sb.AppendLine("{");
        sb.AppendLine("    private const string EmbeddedHtml = @\"");
        
        // Read the embedded HTML resource
        var html = ReadEmbeddedHtmlResource();
        sb.Append(html.Replace("\"", "\"\""));  // Escape quotes for verbatim string
        
        sb.AppendLine("\";");
        sb.AppendLine();
        sb.AppendLine("    public static string GetSwaggerHTML()");
        sb.AppendLine("    {");
        sb.AppendLine("        return EmbeddedHtml;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string JE(string? v)");
        sb.AppendLine("        => v == null ? \"null\" : \"\\\"\" + v.Replace(\"\\\\\", \"\\\\\\\\\").Replace(\"\\\"\", \"\\\\\\\"\").Replace(\"\\n\", \"\\\\n\").Replace(\"\\r\", \"\\\\r\").Replace(\"\\t\", \"\\\\t\") + \"\\\"\";");
        sb.AppendLine();
        sb.AppendLine("    public static string GetEndpointsJson()");
        sb.AppendLine("    {");
        sb.AppendLine("        var endpoints = EndpointsMetadata.GetAllEndpoints();");
        sb.AppendLine("        var json = new System.Text.StringBuilder();");
        sb.AppendLine("        json.Append(\"{\\\"Endpoints\\\":[\");");
        sb.AppendLine("        for (int i = 0; i < endpoints.Count; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            var e = endpoints[i];");
        sb.AppendLine("            if (i > 0) json.Append(',');");
        sb.AppendLine("            json.Append('{');");
        sb.AppendLine("            json.Append(\"\\\"Controller\\\":\"); json.Append(JE(e.Controller));");
        sb.AppendLine("            json.Append(\",\\\"Route\\\":\"); json.Append(JE(e.Route));");
        sb.AppendLine("            json.Append(\",\\\"Method\\\":\"); json.Append(JE(e.Method));");
        sb.AppendLine("            json.Append(\",\\\"Action\\\":\"); json.Append(JE(e.Action));");
        sb.AppendLine("            json.Append(\",\\\"ResponseType\\\":\"); json.Append(JE(e.ResponseType));");
        sb.AppendLine("            json.Append(\",\\\"Summary\\\":\"); json.Append(JE(e.Summary));");
        sb.AppendLine("            json.Append(\",\\\"Parameters\\\":[\");");
        sb.AppendLine("            for (int j = 0; j < e.Parameters.Count; j++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var p = e.Parameters[j];");
        sb.AppendLine("                if (j > 0) json.Append(',');");
        sb.AppendLine("                json.Append('{');");
        sb.AppendLine("                json.Append(\"\\\"Name\\\":\"); json.Append(JE(p.Name));");
        sb.AppendLine("                json.Append(\",\\\"Type\\\":\"); json.Append(JE(p.Type));");
        sb.AppendLine("                json.Append(\",\\\"Source\\\":\"); json.Append(JE(p.Source));");
        sb.AppendLine("                json.Append(\",\\\"IsRequired\\\":\"); json.Append(p.IsRequired ? \"true\" : \"false\");");
        sb.AppendLine("                json.Append('}');");
        sb.AppendLine("            }");
        sb.AppendLine("            json.Append(\"]}\");");
        sb.AppendLine("        }");
        sb.AppendLine("        json.Append(\"]}\");");
        sb.AppendLine("        return json.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static bool TryServeStaticFile(string path, out string content, out string contentType)");
        sb.AppendLine("    {");
        sb.AppendLine("        content = string.Empty;");
        sb.AppendLine("        contentType = \"text/html\";");
        sb.AppendLine();
        sb.AppendLine("        if (path.EndsWith(\"/swagger\") || path.EndsWith(\"/swagger/\") || path.EndsWith(\"/swagger/index.html\"))");
        sb.AppendLine("        {");
        sb.AppendLine("            content = GetSwaggerHTML();");
        sb.AppendLine("            contentType = \"text/html\";");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (path.EndsWith(\"/swagger/api/endpoints.json\"))");
        sb.AppendLine("        {");
        sb.AppendLine("            content = GetEndpointsJson();");
        sb.AppendLine("            contentType = \"application/json\";");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (path.EndsWith(\"/swagger/api.service.ts\"))");
        sb.AppendLine("        {");
        sb.AppendLine("            content = GetTypeScriptService();");
        sb.AppendLine("            contentType = \"text/plain\";");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (path.EndsWith(\"/swagger/lib/bootstrap/bootstrap.min.css\"))");
        sb.AppendLine("        {");
        sb.AppendLine("            content = GetBootstrapCss();");
        sb.AppendLine("            contentType = \"text/css\";");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (path.EndsWith(\"/swagger/lib/bootstrap/bootstrap.bundle.min.js\"))");
        sb.AppendLine("        {");
        sb.AppendLine("            content = GetBootstrapJs();");
        sb.AppendLine("            contentType = \"application/javascript\";");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // Embed Bootstrap CSS as constant
        GenerateBootstrapCssConstant(sb);
        
        // Embed Bootstrap JS as constant
        GenerateBootstrapJsConstant(sb);
        
        sb.AppendLine("    private static string GetTypeScriptService()");
        sb.AppendLine("    {");
        sb.AppendLine("        // Read the generated TypeScript service from the build output");
        sb.AppendLine("        var endpoints = EndpointsMetadata.GetAllEndpoints();");
        sb.AppendLine("        return GenerateTypeScriptFromEndpoints(endpoints);");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        // Generate inline TypeScript generation (simplified version)
        GenerateInlineTypeScriptGenerator(sb);
        
        sb.AppendLine("}");
        
        return sb.ToString();
    }

    private static string ReadEmbeddedHtmlResource()
    {
        var assembly = typeof(SwaggerUIEmitter).Assembly;
        var resourceName = "ZeroReflection.ApiGenerator.Resources.swagger.html";
        
        using var stream = assembly.GetManifestResourceStream(resourceName);
        if (stream == null)
        {
            throw new InvalidOperationException($"Could not find embedded resource: {resourceName}");
        }
        
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private static void GenerateBootstrapCssConstant(StringBuilder sb)
    {
        // Read Bootstrap CSS from embedded resource at build time
        var bootstrapCss = ReadEmbeddedResource("ZeroReflection.ApiGenerator.Resources.lib.bootstrap.bootstrap.min.css");
        
        sb.AppendLine("    private const string BootstrapCss = @\"");
        sb.Append(bootstrapCss.Replace("\"", "\"\""));  // Escape quotes for verbatim string
        sb.AppendLine("\";");
        sb.AppendLine();
        sb.AppendLine("    private static string GetBootstrapCss()");
        sb.AppendLine("    {");
        sb.AppendLine("        return BootstrapCss;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void GenerateBootstrapJsConstant(StringBuilder sb)
    {
        // Read Bootstrap JS from embedded resource at build time
        var bootstrapJs = ReadEmbeddedResource("ZeroReflection.ApiGenerator.Resources.lib.bootstrap.bootstrap.bundle.min.js");
        
        sb.AppendLine("    private const string BootstrapJs = @\"");
        sb.Append(bootstrapJs.Replace("\"", "\"\""));  // Escape quotes for verbatim string
        sb.AppendLine("\";");
        sb.AppendLine();
        sb.AppendLine("    private static string GetBootstrapJs()");
        sb.AppendLine("    {");
        sb.AppendLine("        return BootstrapJs;");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string ReadEmbeddedResource(string resourceName)
    {
        var assembly = typeof(SwaggerUIEmitter).Assembly;
        
        using var stream = assembly.GetManifestResourceStream(resourceName);
        if (stream == null)
        {
            throw new InvalidOperationException($"Could not find embedded resource: {resourceName}");
        }
        
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private static void GenerateInlineTypeScriptGenerator(StringBuilder sb)
    {
        // This method generates C# code that will generate TypeScript at runtime
        sb.AppendLine("    private static string GenerateTypeScriptFromEndpoints(System.Collections.Generic.List<EndpointsMetadata.EndpointInfo> endpoints)");
        sb.AppendLine("    {");
        sb.AppendLine("        var tsBuilder = new System.Text.StringBuilder();");
        sb.AppendLine("        tsBuilder.AppendLine(\"/* Auto-generated TypeScript service from ZeroReflection API */\");");
        sb.AppendLine("        tsBuilder.AppendLine($\"/* Generated at: {System.DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ} */\");");
        sb.AppendLine("        tsBuilder.AppendLine();");
        sb.AppendLine("        tsBuilder.AppendLine(\"import { Injectable } from '@angular/core';\");");
        sb.AppendLine("        tsBuilder.AppendLine(\"import { HttpClient, HttpParams } from '@angular/common/http';\");");
        sb.AppendLine("        tsBuilder.AppendLine(\"import { Observable } from 'rxjs';\");");
        sb.AppendLine("        tsBuilder.AppendLine();");
        sb.AppendLine("        tsBuilder.AppendLine(\"@Injectable({ providedIn: 'root' })\");");
        sb.AppendLine("        tsBuilder.AppendLine(\"export class ApiService {\");");
        sb.AppendLine("        tsBuilder.AppendLine(\"  private baseUrl = '/api';\");");
        sb.AppendLine("        tsBuilder.AppendLine(\"  constructor(private http: HttpClient) {}\");");
        sb.AppendLine("        tsBuilder.AppendLine(\"\");");
        sb.AppendLine("        ");
        sb.AppendLine("        var grouped = endpoints.GroupBy(e => e.Controller).OrderBy(g => g.Key);");
        sb.AppendLine("        foreach (var group in grouped)");
        sb.AppendLine("        {");
        sb.AppendLine("            tsBuilder.AppendLine($\"  // {group.Key}\");");
        sb.AppendLine("            foreach (var endpoint in group)");
        sb.AppendLine("            {");
        sb.AppendLine("                var methodName = char.ToLowerInvariant(endpoint.Action[0]) + endpoint.Action.Substring(1);");
        sb.AppendLine("                tsBuilder.AppendLine($\"  {methodName}(): Observable<any> {{ return this.http.{endpoint.Method.ToLowerInvariant()}<any>('{endpoint.Route}'); }}\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        ");
        sb.AppendLine("        tsBuilder.AppendLine(\"}\");");
        sb.AppendLine("        return tsBuilder.ToString();");
        sb.AppendLine("    }");
    }
}
