using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZeroReflection.MediatorGenerator.Emit
{
    internal static class DispatcherEmitter
    {
        public static string Build(List<HandlerInfo> handlers, HashSet<string> namespaces, bool useSwitchDispatcher)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using ZeroReflection.Mediator;");
            
            foreach (var ns in namespaces.Where(n => !string.IsNullOrWhiteSpace(n) && 
                                                      n != "ZeroReflection.Mediator" &&
                                                      n != "Microsoft.Extensions.DependencyInjection")
                                         .OrderBy(n => n))
            {
                sb.AppendLine($"using {ns};");
            }
            
            sb.AppendLine();
            sb.AppendLine("namespace ZeroReflection.Mediator.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class __GeneratedMediatorDispatcherStatic");
            sb.AppendLine("    {");

            // Build lookup dictionaries if using switch dispatcher
            if (useSwitchDispatcher)
            {
                // Handler lookup
                sb.AppendLine("        private static readonly System.Collections.Generic.Dictionary<(System.Type, System.Type), int> _handlerIndex = new()");
                sb.AppendLine("        {");
                int handlerIdx = 1;
                foreach (var handler in handlers)
                {
                    sb.AppendLine($"            {{ (typeof({handler.RequestType}), typeof({handler.ResponseType})), {handlerIdx++} }},");
                }
                sb.AppendLine("        };");
                sb.AppendLine();

                // Validator lookup
                var validatorTypes = handlers.Select(h => h.RequestType).Distinct().ToList();
                sb.AppendLine("        private static readonly System.Collections.Generic.Dictionary<System.Type, int> _validatorIndex = new()");
                sb.AppendLine("        {");
                int validatorIdx = 1;
                foreach (var reqType in validatorTypes)
                {
                    sb.AppendLine($"            {{ typeof({reqType}), {validatorIdx++} }},");
                }
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            // TryHandle method
            GenerateTryHandleMethod(sb, handlers, useSwitchDispatcher);
            sb.AppendLine();

            // TryValidate method
            GenerateTryValidateMethod(sb, handlers, useSwitchDispatcher);

            sb.AppendLine("    }");
            sb.AppendLine();

            // Public wrapper class
            sb.AppendLine("    public sealed class GeneratedMediatorDispatcher : IGeneratedMediatorDispatcher");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly System.IServiceProvider _serviceProvider;");
            sb.AppendLine();
            sb.AppendLine("        public GeneratedMediatorDispatcher(System.IServiceProvider serviceProvider)");
            sb.AppendLine("        {");
            sb.AppendLine("            _serviceProvider = serviceProvider;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public Task<(bool handled, object result)> TryHandle(object request, Type requestType, Type responseType, CancellationToken cancellationToken)");
            sb.AppendLine("            => __GeneratedMediatorDispatcherStatic.TryHandle(request, requestType, responseType, _serviceProvider, cancellationToken);");
            sb.AppendLine();
            sb.AppendLine("        public bool TryValidate(object request, Type requestType)");
            sb.AppendLine("            => __GeneratedMediatorDispatcherStatic.TryValidate(request, requestType, _serviceProvider);");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void GenerateTryHandleMethod(StringBuilder sb, List<HandlerInfo> handlers, bool useSwitchDispatcher)
        {
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        internal static async Task<(bool handled, object result)> TryHandle(object request, Type requestType, Type responseType, System.IServiceProvider serviceProvider, CancellationToken cancellationToken)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (request is null) { return (false, null!); }");

            if (useSwitchDispatcher)
            {
                sb.AppendLine("            if (!_handlerIndex.TryGetValue((requestType, responseType), out int key)) { return (false, null!); }");
                sb.AppendLine("            switch (key)");
                sb.AppendLine("            {");
                
                int caseIdx = 1;
                foreach (var handler in handlers)
                {
                    sb.AppendLine($"                case {caseIdx++}:");
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    var handler = (IRequestHandler<{handler.RequestType}, {handler.ResponseType}>)serviceProvider.GetService(typeof(IRequestHandler<{handler.RequestType}, {handler.ResponseType}>));");
                    sb.AppendLine($"                    if (handler == null) {{ return (false, null!); }}");
                    sb.AppendLine($"                    var result = await handler.Handle(({handler.RequestType})request, cancellationToken);");
                    sb.AppendLine($"                    return (true, result);");
                    sb.AppendLine($"                }}");
                }
                
                sb.AppendLine("                default: return (false, null!);");
                sb.AppendLine("            }");
            }
            else
            {
                foreach (var handler in handlers)
                {
                    sb.AppendLine($"            if (requestType == typeof({handler.RequestType}) && responseType == typeof({handler.ResponseType}))");
                    sb.AppendLine($"            {{");
                    sb.AppendLine($"                var handler = (IRequestHandler<{handler.RequestType}, {handler.ResponseType}>)serviceProvider.GetService(typeof(IRequestHandler<{handler.RequestType}, {handler.ResponseType}>));");
                    sb.AppendLine($"                if (handler == null) {{ return (false, null!); }}");
                    sb.AppendLine($"                var result = await handler.Handle(({handler.RequestType})request, cancellationToken);");
                    sb.AppendLine($"                return (true, result);");
                    sb.AppendLine($"            }}");
                }
                sb.AppendLine("            return (false, null!);");
            }

            sb.AppendLine("        }");
        }

        private static void GenerateTryValidateMethod(StringBuilder sb, List<HandlerInfo> handlers, bool useSwitchDispatcher)
        {
            var validatorTypes = handlers.Select(h => h.RequestType).Distinct().ToList();

            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        internal static bool TryValidate(object request, Type requestType, System.IServiceProvider serviceProvider)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (request is null) { return false; }");

            if (useSwitchDispatcher)
            {
                sb.AppendLine("            if (!_validatorIndex.TryGetValue(requestType, out int key)) { return false; }");
                sb.AppendLine("            switch (key)");
                sb.AppendLine("            {");
                
                int caseIdx = 1;
                foreach (var reqType in validatorTypes)
                {
                    sb.AppendLine($"                case {caseIdx++}:");
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    var validator = (IValidator<{reqType}>)serviceProvider.GetService(typeof(IValidator<{reqType}>));");
                    sb.AppendLine($"                    if (validator != null)");
                    sb.AppendLine($"                    {{");
                    sb.AppendLine($"                        validator.Validate(({reqType})request);");
                    sb.AppendLine($"                        return true;");
                    sb.AppendLine($"                    }}");
                    sb.AppendLine($"                    return false;");
                    sb.AppendLine($"                }}");
                }
                
                sb.AppendLine("                default: return false;");
                sb.AppendLine("            }");
            }
            else
            {
                foreach (var reqType in validatorTypes)
                {
                    sb.AppendLine($"            if (requestType == typeof({reqType}))");
                    sb.AppendLine($"            {{");
                    sb.AppendLine($"                var validator = (IValidator<{reqType}>)serviceProvider.GetService(typeof(IValidator<{reqType}>));");
                    sb.AppendLine($"                if (validator != null)");
                    sb.AppendLine($"                {{");
                    sb.AppendLine($"                    validator.Validate(({reqType})request);");
                    sb.AppendLine($"                    return true;");
                    sb.AppendLine($"                }}");
                    sb.AppendLine($"            }}");
                }
                sb.AppendLine("            return false;");
            }

            sb.AppendLine("        }");
        }
    }

    internal class HandlerInfo
    {
        public string RequestType { get; set; }
        public string ResponseType { get; set; }
        public string HandlerType { get; set; }
        public string Namespace { get; set; }
    }
}
